fix build

diff --git a/dashboard/Dockerfile b/dashboard/Dockerfile
--- a/dashboard/Dockerfile
+++ b/dashboard/Dockerfile
@@ -1,28 +1,77 @@
+# Base image
+FROM node:18-alpine AS base
+
 # Install dependencies only when needed
-FROM node:18-alpine AS deps
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
-COPY package.json yarn.lock* ./
-RUN yarn install --frozen-lockfile
+
+# Copy package.json and lock files
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+
+# Install dependencies based on the preferred package manager
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 # Rebuild the source code only when needed
-FROM node:18-alpine AS builder
+FROM base AS builder
 WORKDIR /app
 COPY --from=deps /app/node_modules ./node_modules
 COPY . .
+
+# Pass build-time environment variables
 ARG BUILDTIME_ENV_VARS
 ENV BUILDTIME_ENV_VARS=${BUILDTIME_ENV_VARS}
-RUN yarn build
+
+# Build the application
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 # Production image, copy all the files and run next
-FROM node:18-alpine AS runner
+FROM base AS runner
 WORKDIR /app
 ENV NODE_ENV production
-COPY --from=builder /app/next.config.mjs ./
+
+# Create a non-root user
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+# Copy necessary files
 COPY --from=builder /app/public ./public
-COPY --from=builder /app/package.json ./
-COPY --from=builder /app/.next ./.next
-COPY --from=builder /app/node_modules ./node_modules
+COPY --from=builder /app/package.json ./package.json
+
+# Set the correct permission for prerender cache
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+# Pass runtime environment variables
 ARG DASHBOARD_ENV_VARS
 ENV DASHBOARD_ENV_VARS=${DASHBOARD_ENV_VARS}
-EXPOSE 3000
-CMD ["node_modules/.bin/next", "start"]
+
+USER nextjs
+
+# Expose port 80
+EXPOSE 80
+
+# Set the host to 0.0.0.0 to make the server accessible externally
+ENV HOSTNAME "0.0.0.0"
+
+# Set the port to 80
+ENV PORT 80
+
+# Start the application
+CMD ["node", "server.js"]
